TorneioDeLuta/Controllers/TorneioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using TorneioDeLuta.Modelo;
using TorneioDeLuta.DTO;
using TorneioDeLuta.Negocios;

namespace TorneioDeLuta.Controllers
{
    public class TorneioController : Controller
    {
        private Inteligencia torneio = new Inteligencia(); 

        [HttpGet]
        public ActionResult Index()
        {            
            return View(torneio.GetLutadores());
        }

        public ActionResult Selecionar(int id, bool check)
        {
            torneio.SetSelecionaLutador(id, check);
            return RedirectToAction("Index");
        }

        public ActionResult Resultado(List<Lutador> lutadores)
        {
            if (torneio.GetLutadoresSelecionados().Count() == 20)
            {
                return View(
                        torneio.IniciaTorneio(lutadores).Where(c => c.classificacaoFinal == 1 || c.classificacaoFinal == 2 || c.classificacaoFinal == 3).OrderBy(c => c.classificacaoFinal)
                );                
            }
            else
            {
                return RedirectToAction("Index");
            }            
        }

        public List<Grupos> DivisaoDeGrupos(List<Lutador> Participantes)
        {           
            return torneio.DivisaoDeGrupos(Participantes);
        }        
    }
}

TorneioDeLuta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container text-center">
        <h1>Torneio de Luta</h1>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TorneioDeLuta/Views/Torneio/Index.cshtml
@model IEnumerable<TorneioDeLuta.Modelo.Lutador>

@{
    ViewBag.Title = "Torneio de Luta";
}


@using (Html.BeginForm("Resultado", "Torneio", "post"))
{
    <div class="container">
        <input class="btn btn-primary" type="submit" id="submitButton" value="Iniciar" name="Iniciar" />
    </div>
    <br />
    <div class="container">
        Qtd.Lutadores Selecionados: @Model.Where(m => m.selecionado).Count()
    </div>
}

<div class="container row" style="width:auto">
    @foreach (var item in Model)
    {
        <div class="col-lg-2">
            <div class="card" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h6>
                            @{
                                var url = Url.Action("Selecionar", "Torneio", new { Id = item.id, check = !item.selecionado }, null);
                            }
                            @Html.CheckBox("mycheckbox", item.selecionado, new { onclick = "window.location = '" + url + "'" })

                            <strong> @Html.DisplayFor(modelItem => item.nome)</strong>
                        </h6>
                    </li>
                    <li class="list-group-item">
                        <div class="container-fluid pre-scrollable" style="height:90px">
                            <p><strong>Idade:</strong> @Html.DisplayFor(modelItem => item.idade)</p>
                            <p><strong>Lutas:</strong> @Html.DisplayFor(modelItem => item.lutas)</p>
                            <p><strong>Derrotas:</strong> @Html.DisplayFor(modelItem => item.derrotas)</p>
                            <p><strong>Vitórias:</strong> @Html.DisplayFor(modelItem => item.vitorias)</p>
                            <p><strong>Artes Marciais:</strong> @Html.DisplayFor(modelItem => item.artesMarciais)</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    }

</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#submitButton").on("click", function () {
                if (@Model.Where(m => m.selecionado).Count() != 20) {
                    alert('Selecione 20 Lutadores!')                
                }                
            });
        });
    </script>
}

TorneioDeLuta/Views/Torneio/Resultado.cshtml
@model IEnumerable<TorneioDeLuta.Modelo.Grupos>

@{
    ViewBag.Title = "Resultado";
}

<div class="container">
    <div class="container">
        @Html.ActionLink("Voltar","Index","Torneio",null, new
        {
            @class = "btn btn-sm btn-primary glyphicon glyphicon-arrow-left center"
        })
    </div>
    <br />
    <div class="container">
        @foreach (var item in Model)
        {
            <div @*class="col-lg-4"*@>
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            @switch (item.classificacaoFinal)
                            {
                                case 1:<strong> Campeão</strong>
                                    break;
                                case 2: <strong> Segundo</strong>
                                    break;
                                case 3: <strong> Terceiro</strong>
                                    break;
                            }

                        </li>
                        <li class="list-group-item">
                            <div class="container-fluid">
                                <p>@Html.DisplayFor(modelItem => item.nome)</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        }
    </div>
</div>